<?php

/**
 * @file
 * Module to integrate Ubercart with CiviCRM.
 */

/**
 * Implementation of hook_help().
 */
function uc_civicrm_help($path = 'admin/help#uc_civicrm') {
  if (!module_exists('civicrm')) { return; }
  switch ($path) {
    case 'admin/help#uc_civicrm':
      return t('This module integrates Ubercart with CiviCRM. When a customer buys something from the store, the name and address information they provide is added to CiviCRM. Existing contact records will be updated. The new or updated contact is added to a group, activity history record of type \'Purchase\' is added to the contact\'s history and the \'Purchases\' tab on the contact\'s dashboard is populated with a link to their order history.');
  }
}


/**
 * Implementation of hook_civicrm_tabs().
 */
function uc_civicrm_civicrm_tabs(&$tabs, $cid) {
  if (!civicrm_initialize()) { return; }
  $uid = CRM_Core_BAO_UFMatch::getUFId($cid);
  if (empty($uid)) { return; }

  $count = _uc_civicrm_customer_orders_count($uid);
  $tab = array(
    'id'     => 'purchases',
    'title'  => t('Purchases'),
    'count'  => $count,
    'weight' => 99,
  );

  if ($count > 0) { $tab['url'] = url("admin/store/civicrm/customer/orders/$uid"); }
  $tabs[] = $tab;

  return $tabs;
}


/**
 * Implementation of hook_menu().
 */
function uc_civicrm_menu() {
  if (!module_exists('civicrm')) { return; }

  $items = array();
  $items['admin/store/civicrm/customer/orders/%'] = array(
    'title'            => 'CiviCRM',
    'page callback'    => 'uc_civicrm_contact_transaction',
    'page arguments'   => array(5),
    'access arguments' => array('administer CiviCRM'),
    'type'             => MENU_CALLBACK,
  );

  $items['admin/settings/uc_civicrm_menu'] = array(
    'title' => 'Ubercart/CiviCRM',
    'description' => 'Configuration options for Ubercart/CiviCRM integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_civicrm_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Callback to expose order information in a CiviCRM tab.
 * (more limited that d7 version of same)
 *
 * @param $uid
 *   Drupal UID for the customer
 */
function uc_civicrm_contact_transaction($uid, $snippet = TRUE) {
  if (!module_exists('civicrm') || is_null($uid)) { return; }
  if (!civicrm_initialize()) { return; }

  $output = _uc_civicrm_customer_orders($uid);
  if ($snippet) { print ($output); }
  else { return $output; }
  return;
}

/**
 *  Admin form configuration.
 */
function uc_civicrm_admin() {
  if (!module_exists('civicrm')) { return; }
  if (!civicrm_initialize()) { return; }

  $groups = civicrm_api3('group', 'get', array());

  $options = array();
  foreach ($groups['values'] as $group) {
    $options[$group['id']] = $group['title']; }
    //Modified by BOT - 1st July, 2013
    natsort($options);

  // Get contribution types
  $sql = "SELECT id, name FROM civicrm_contribution_type WHERE is_active = 1";
  $dao =& CRM_Core_DAO::executeQuery($sql, array());
  $types = array(0 => "Select a type...");
  while ($dao->fetch()) { $types[$dao->id] = $dao->name; }

  $form = array();
  $form['uc_civicrm_contribution_type'] = array(
    '#type' => 'select',
    '#title' => t('Contribution type'),
    '#default_value' => variable_get('uc_civicrm_contribution_type', array()),
    '#options' => $types,
    '#description' => t('Select a contribution type for purchases, making a new type with a name like "Ubercart purchase" is recommended.'),
  );

  $form['uc_civicrm_groups'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Groups to add purchasers to'),
    '#default_value' => variable_get('uc_civicrm_groups', array()),
    '#options' => $options,
    '#description' => t('Check to add purchasers to the selected groups')
  );

  return system_settings_form($form);
}


/**
 *  Implementation of Ubercart conditional action hook_ca_predicate().
 *
 *  Tell Ubercart to let us know when an order is complete
 */
function uc_civicrm_ca_predicate() {
  if (!module_exists('civicrm')) { return; }

  $predicates['uc_civicrm_contact_on_order'] = array(
    '#title'   => t('Copy to CiviCRM upon order submission'),
    '#trigger' => 'uc_checkout_complete',
    '#class'   => 'uc_civicrm',
    '#status'  => 1,
    '#actions' => array(
      array(
        '#name'         => 'uc_civicrm_action_update_contact',
        '#title'        => t('Copy order information to CiviCRM'),
        '#argument_map' => array('order' => 'order',),
      ),
    ),
  );

  $predicates['uc_civicrm_check_order_status'] = array(
    '#title'   => t('Sync CiviCRM status on status update'),
    '#trigger' => 'uc_order_status_update',
    '#class'   => 'uc_civicrm',
    '#status'  => 1,
    '#actions' => array(
      array(
        '#name'         => 'uc_civicrm_sync_status',
        '#title'        => t('Syncronize status'),
        '#argument_map' => array('order' => 'updated_order',),
      ),
    ),
  );

  return $predicates;
}


/**
 * Implementation of Ubercart conditional action hook_ca_action().
 */
function uc_civicrm_ca_action() {
  if (!module_exists('civicrm')) { return; }

  $order_arg = array('#entity' => 'uc_order', '#title'  => t('Order'),);

  $actions['uc_civicrm_action_update_contact'] = array(
    '#title'     => t('Inform CiviCRM upon order submission'),
    '#category'  => t('Order'),
    '#callback'  => 'uc_civicrm_action_update_contact',
    '#arguments' => array('order' => $order_arg,),
  );

  $actions['uc_civicrm_sync_status'] = array(
    '#title'     => t('Syncronize order status with CiviCRM when changed'),
    '#category'  => t('Order'),
    '#callback'  => 'uc_civicrm_synchronize_status',
    '#arguments' => array('order' => $order_arg,),
  );

  $actions['uc_civicrm_create_activity'] = array(
      '#title'     => t('Create CiviCRM activity'),
      '#category'  => t('Order'),
      '#callback'  => 'uc_civicrm_create_activity',
      '#arguments' => array('order' => $order_arg,),
  );
  return $actions;
}


/**
 * Callback to inform CiviCRM on order complete
 *
 * Called when the conditional action trigger 'uc_checkout_complete'
 * is pulled, with the order information.  Merge the information
 * in the order into the CiviCRM contact database.
 *
 * @param $order
 *   Order
 */
function uc_civicrm_action_update_contact($order) {
  global $user;

  if (!civicrm_initialize(TRUE)) {
    return;
  }
  $cid = _uc_civicrm_get_cid($order);
  if ($cid === false) {
    watchdog('uc_civicrm', '_uc_civicrm_get_cid() returned '. $cid, array(), WATCHDOG_ERROR);
    return;
  }

  $cid = _uc_civicrm_add_update_contact($cid, $order);
  if ($cid === false) {
    watchdog('uc_civicrm', '_uc_civicrm_add_update_contact() returned '. $cid, array(), WATCHDOG_ERROR);
    return;
  }
  _uc_civicrm_add_to_groups($cid);
}

/**
 * Called when the an order is created or changed. Creates a new order or
 * updates an existing one.
 *
 * @param $order
 *   the order
 * @param $is_new boolean
 *   TRUE if it's a new order
 */
function uc_civicrm_action_order_civicrm($order, $is_new = TRUE) {
  global $user;

  if (!module_exists('civicrm')) { return; }
  if (!civicrm_initialize()) { return; }
  if ($is_new) {
    require_once 'api/v2/Contact.php';

    // Find or create a CiviCRM contact ID for the customer.
    $cid = _uc_civicrm_get_cid($order);
    if ($cid === FALSE) { return; }

    $cid = _uc_civicrm_add_update_contact($cid, $order);

    if ($cid === FALSE) { return; }

    // add the contribution record
    _uc_civicrm_add_contribution($cid, $order);

    // add this contact to selected groups
    _uc_civicrm_add_to_groups($cid);
  } else {
    require_once "api/v2/Contribute.php";
    $config =& CRM_Core_Config::singleton();
    $params = array('invoice_id' => $order->order_id . "_uc", 'return.contact_id' => 1, );
    $result =& civicrm_contribution_search($params);
    if (civicrm_error($result)) {
      watchdog('uc_civicrm', 'Error searching for contribution: ' . $result['error_message'], array(), WATCHDOG_ERROR);
    } else {
      $contribution = array_shift($result);
      $params = array(
        'id' => $contribution['contribution_id'],
        'contact_id' => $contribution['contact_id'],
        'contribution_status_id' => _uc_civicrm_map_contribution_status($order->order_status),
      );
      $result =& civicrm_contribution_add($params);

      // @TODO There is a very odd issue here, evidently the system works,
      // but there are times when this fires before a contribution has been added.
      if (civicrm_error ($result)) {
        watchdog('uc_civicrm', 'Error updating contribution: ' . $result['error_message'], array(), WATCHDOG_ERROR);
      }
    }
  }
}


/**
 * Add contact to any specified groups.
 *
 * @param $contact
 *   CRM_Contact_BAO_Group object describing the contact to add
 */
function _uc_civicrm_add_to_groups($cid) {
  require_once 'api/v2/GroupContact.php';

  // No groups specified
  $groups = variable_get('uc_civicrm_groups', '');
  if ($groups == '') { return; }

  foreach ($groups as $id => $key) {
    if ($key != 0) {
      $params = array('contact_id' => $cid, 'group_id' => $key);
      $result = civicrm_group_contact_add($params);
      if (!empty($result['is_error'])) {
        watchdog('uc_civicrm', 'Error adding contact to group: ' . $result['error_message'], array(), WATCHDOG_ERROR);
      }
    }
  }
}


/**
 * Get contact id for the customer.
 *
 * @param $order
 *   Order
 * @return
 *   false|integer false   => an error occured
 *                 integer => CID if non-zero; must create if zero
 */
function _uc_civicrm_get_cid($order) {
  if (!module_exists('civicrm')) {
    return;
  }

  if ($order->uid != 0) {
    $match = CRM_Core_BAO_UFMatch::synchronizeUFMatch($user, $order->uid, $order->primary_email, 'Drupal', FALSE, 'Individual');
    if (!is_object($match)) { return FALSE; }
    return $match->contact_id;
  }

  // The customer is anonymous.  Look in the CiviCRM contacts table for a
  // contact that matches the primary email.
  $params = array('email' => $order->primary_email, 'return.contact_id' => TRUE);
  $contact = civicrm_contact_search($params);
  if (!empty($contact['is_error'])) {
    watchdog('uc_civicrm', 'civicrm_contact_search(): ' . $contact['error_message'], array(), WATCHDOG_ERROR);

    return FALSE;
  }

  // No matches found, so we will need to create a contact.
  if (count($contact) == 0) { return 0; }
  $cid = array_shift($contact);
  return $cid;
}


/**
 *  Add or update contact information
 */
function _uc_civicrm_add_update_contact($cid, $order) {
  if(!civicrm_initialize(TRUE)){
    return;
  }
  require_once 'api/v2/Location.php';

  $contact = array();
  if ($cid != 0) {
    try {
      $params = array(
        'contact_id' => $cid,
        'return' => array('id', 'source', 'first_name', 'last_name',)
      );
      $contact = civicrm_api3('contact', 'getsingle', $params);
    }
    catch(CiviCRM_Exception $e) {
      watchdog('uc_civicrm', 'civicrm_contact_get():' . $e->getMessage(), array(), WATCHDOG_ERROR);
      return FALSE;
    }
  }

  //Determine if the contact is new - added by bot
  $log = new CRM_Core_DAO_Log();
  $log->entity_table = 'civicrm_contact';
  $log->entity_id = $cid;
  $log->orderBy('modified_date asc');
  $log->limit(1);
  $result = CRM_Core_DAO::$_nullObject;
  if ($log->find(TRUE)) {
    $result = array(
        'id' => $log->modified_id,
        'date' => $log->modified_date,
     );
  }
  $date = date('Y-m-d H:i:s');
  $to_time = strtotime($date);
  $from_time = strtotime($result['date']);
  $diff = round(abs($to_time - $from_time) / 60,2). " minute";
  $contactStatus = 'old';
  if ( $diff < 30 ) {
    $contactStatus = 'new';
  }

  $contactParams = array(
    'id' => $cid,
    'version' => 3,
  );

  $contactInfo = civicrm_api( 'contact','get', $contactParams );
  // Prepare array to update contact via civi API
  // Assume that if there is a delivery name then that is the contact to add
  $fname = '';
  $lname = '';
  if (!empty($order->delivery_last_name) && !empty($order->delivery_first_name)) {
    $fname = $order->delivery_first_name;
    $lname = $order->delivery_last_name;
  } else {
    $fname = $order->billing_first_name;
    $lname = $order->billing_last_name;
  }

  $contact['last_name'] = $lname;
  $contact['first_name'] = $fname;
  $contact['sort_name'] = "{$lname}, {$fname}";
  $contact['display_name'] = "{$fname} {$lname}";
  $contact['contact_type'] = 'Individual';
  $contact['email'] = $order->primary_email;
  if (empty($contact['source'])) { $contact['source'] = 'Ubercart purchase'; }
  $contact['version'] = 3;
  // Create contact or update existing contact
  if ( $contactStatus == 'new' && !$contactInfo['values'][$cid]['first_name'] && !$contactInfo['values'][$cid]['last_name']) {
    $result = civicrm_api('contact', 'create', $contact);

if (!empty($result['is_error'])) {
   watchdog('uc_civicrm', 'civicrm_contact_add():' . $rc['error_message'], array(), WATCHDOG_ERROR);
   return FALSE;
 }
}
  // Location
  $loc_types = CRM_Core_PseudoConstant::locationType();

  $uc_billing = array_search( 'Ubercart_Billing', $loc_types);
  $uc_shipping = array_search('Ubercart_Shipping', $loc_types);
  if (!empty($order->delivery_last_name) && !empty($order->delivery_first_name)) {
    $deliveryPhone = array();
    if (!empty($order->delivery_phone)) {
      $deliveryPhone = array(
        'phone' => $order->delivery_phone,
        'phone_type_id' => 1,
        'location_type_id' => $uc_shipping
      );
    }

    $countries = uc_get_country_data(array('country_id' => $order->delivery_country));
    $address = array(
      1 => array(
        'location_type_id'       => $uc_shipping,
        'city'                   => $order->delivery_city,
        'state_province'         => uc_get_zone_code($order->delivery_zone),
        'postal_code'            => $order->delivery_postal_code,
        'name'                   => $order->delivery_company,
        'street_address'         => $order->delivery_street1,
        'supplemental_address_1' => $order->delivery_street2,
        'country'                => $countries[0]['country_iso_code_2']
      )
    );

    // Delivery Phone
    $phones = array($deliveryPhone);
    $params = array('version' => '3.0', 'contact_id' => $cid, 'phone' => $phones, 'address' => $address);
    $newLocation = civicrm_location_update($params);
    if ($newLocation['is_error'] &&
        strpos($newLocation['error_message'], "Invalid Location Type(s) : Ubercart_Shipping") !== FALSE) {
      $newLocation = civicrm_location_add($params);
    }
    // Log the error, but continue.
    if (civicrm_error($newLocation)) {
      watchdog('uc_civicrm', 'civicrm_location_update(): ' . $newLocation['error_message'], array(), WATCHDOG_ERROR);
    }
  }

  // Billing phone
  $billingPhone = array();
  if (!empty($order->billing_phone)) {
    $billingPhone = array(
      'phone' => $order->billing_phone,
      'is_primary' => FALSE,
      'phone_type_id' => 1,
      'location_type_id' => $uc_billing,
    );
  }

  $countries = uc_get_country_data(array('country_id' => $order->billing_country));
  $address = array(
    1 => array(
      'location_type_id'          => $uc_billing, //Billing', // this assumes the billing address type id == 5
      'city'                   => $order->billing_city,
      'state_province'         => uc_get_zone_code($order->billing_zone),
      'postal_code'            => $order->billing_postal_code,
      'name'                   => $order->billing_company,
      'street_address'         => $order->billing_street1,
      'supplemental_address_1' => $order->billing_street2,
      'country'                => $countries[0]['country_iso_code_2']
    )
  );

  $phones = array($billingPhone);
  $params = array('version' => '3.0', 'contact_id' => $cid, 'phone' => $phones, 'address' => $address);
  $newBillingLocation = civicrm_location_update($params);
  if ($newBillingLocation['is_error'] &&
      strpos($newBillingLocation['error_message'], "Invalid Location Type(s) : Ubercart_Billing") !== FALSE) {
    $newBillingLocation = civicrm_location_add($params);
  }
  // Log the error, but continue.
  if (civicrm_error($newBillingLocation)) {
    watchdog('uc_civicrm', 'civicrm_location_update(): ' . $newBillingLocation['error_message'], array(), WATCHDOG_ERROR);
  }

  return $cid;
}


/**
 * Creates required contribution fields if they have not already been created.
 */
function _uc_civicrm_create_custom_contribution_fields() {
  $groupId = variable_get('uc_civicrm_contribution_group_id', FALSE);
  if ($groupId != FALSE) { return; }

  require_once 'api/v2/CustomGroup.php';
  // First we need to check if the Sales Tax and Shipping custom fields have
  // already been created.
  $params = array(
    'title'            => 'Ubercart Purchases',
    'name'             => 'ubercart_purchases',
    'extends'          => array('Contribution'),
    'weight'           => 1,
    'collapse_display' => 0,
    'is_active'        => 1,
  );
  $customGroup = civicrm_custom_group_create($params);
  variable_set('uc_civicrm_contribution_group_id', $customGroup['id']);

  $params = array(
    'custom_group_id' => $customGroup['id'],
    'label'           => 'Sales Tax',
    'html_type'       => 'Text',
    'data_type'       => 'String',
    'weight'          => 1,
    'is_required'     => 0,
    'is_searchable'   => 0,
    'is_active'       => 1,
  );
  $taxField = civicrm_custom_field_create($params);
  variable_set('uc_civicrm_sales_tax_field_id', $taxField['result']['customFieldId']);

  $params = array(
    'custom_group_id' => $customGroup['id'],
    'label'           => 'Shipping Cost',
    'html_type'       => 'Text',
    'data_type'       => 'String',
    'weight'          => 2,
    'is_required'     => 0,
    'is_searchable'   => 0,
    'is_active'       => 1,
  );
  $shippingField = civicrm_custom_field_create($params);
  variable_set('uc_civicrm_shipping_cost_field_id', $shippingField['result']['customFieldId']);
}


/**
 * Add a contribution record
 *
 * Create any custom fields and get the transaction id. If it doesn't exist,
 * make one up and add the contribution.
 */
function _uc_civicrm_add_contribution($cid, &$order) {
  if(!civicrm_initialize()){
    return;
  }
  _uc_civicrm_create_custom_contribution_fields();

  $payDataAry = uc_payment_load_payments($order->order_id);
  $payDataAry[0]->data = unserialize($payDataAry[0]->data);
  $txnId = isset($payDataAry[0]->data['txn_id']) ?
      $payDataAry[0]->data['txn_id'] : 'TRXN ID NOT AVAILABLE ' . md5($order->order_id);

  // @FIXME Landmine. CiviCRM doesn't seem to accept financial values with
  // precision greater than 2 digits after the decimal.
  $roundedTotal = round($order->order_total * 100) / 100;

  $salesTaxFieldId = 'custom_' . variable_get('uc_civicrm_sales_tax_field_id', '');
  $shippingCostFieldId = 'custom_' . variable_get('uc_civicrm_shipping_cost_field_id', '');
  $taxCost = '';
  $shippingCost = '';

  foreach ($order->line_items as $item) {
    if ($item['type'] == 'tax') { $taxCost = $item['amount']; }
    elseif ($item['type'] == 'shipping') { $shippingCost = $item['amount']; }
  }

  $params = array(
    'contact_id' => $cid,
    'receive_date' => date('Ymd'),
    'total_amount' => $roundedTotal,
    'contribution_type_id' => variable_get('uc_civicrm_contribution_type', ''), // @FIXME this needs a sensible default
    'payment_instrument_id' => _uc_civicrm_map_payment_instrument($order->payment_method),
    'non_deductible_amount' => 00.00,
    'fee_amount' => 00.00,
    'net_amount' => $roundedTotal,
    'trxn_id' => $txnId,
    'invoice_id' => $order->order_id . '_uc',
    'source' => _uc_civicrm_create_detail_string($order),
    'contribution_status_id' => _uc_civicrm_map_contribution_status($order->order_status),
    'note' => _uc_civicrm_create_detail_string($order),
    "$salesTaxFieldId" => $taxCost,
    "$shippingCostFieldId" => $shippingCost,
    'version' => 3,
  );

  $contribution = civicrm_api('Contribution', 'create', $params);

  // Log the error, but continue.
  if (civicrm_error($contribution)) {
    watchdog('uc_civicrm', 'civicrm_contribution_add(): ' . $contribution['error_message'], array(), WATCHDOG_ERROR);
  }

  return TRUE;
}


/**
 * Maps an Ubercart payment method to a CiviCRM payment instrument
 *
 * @param string $paymentDevice
 *    An Ubercart payment device
 * @return int
 *    The CiviCRM id of the payment processor
 */
function _uc_civicrm_map_payment_instrument($paymentDevice) {
  // Note that the payment methods for Ubercart are hardcoded in the payment
  // modules under hook_uc_payment_method(), so anything that's not explicitly a
  // check or cash has to be a credit card.
  $map = array(
    "credit" => 1,
    "cod"    => 3,
    "check"  => 4,
  );

  if (array_key_exists($paymentDevice, $map)) { $id = $map[$paymentDevice]; }
  else { $id = 1; } // Another Ubercart payment method - good chance this is credit.

  return $id;
}


/**
 * Maps an Ubercart order status to a corresponding CiviCRM contribution status
 *
 * @param string $orderStatus
 *    An Ubercart order status
 * @return int
 *    A CiviCRM order status
 */
function _uc_civicrm_map_contribution_status($orderStatus) {
  // NOTE: There may be a more "correct" way to do this.
  $map = array(
    "completed"        => 1,
    "payment_received" => 1,
    "pending"          => 2,
    "processing"       => 5,
    "canceled"         => 3,
    "in_checkout"      => 5,
  );

  if (array_key_exists($orderStatus, $map)) { $id = $map[$orderStatus]; }
  else {
    $id = 1; // Oh no.
    watchdog('uc_civicrm', 'There is no status that maps to ' . $orderStatus . ', marking as "Complete"', array(), WATCHDOG_WARNING);
  }

  return $id;
}
/**
 * Create activity in Civi
 */
function uc_civicrm_create_activity($order, $arguments) {
  if(!civicrm_initialize(TRUE)) {
    return;
  }
  if(user_is_logged_in() == FALSE) {
    return;
  }
  try{
    civicrm_api3('activity', 'create', $arguments);
  }
  catch(CiviCRM_API3_Exception $e) {
    drupal_set_message('activity creation failed ' . $e->getmessage());
    watchdog('uc_civicrm', 'activity creation failed ' . $e->getmessage());
  }
}

/**
 * Create activity in Civi
 */
function uc_civicrm_create_activity_form($form_state, $settings = array()) {
  if(!civicrm_initialize(TRUE)) {
    return;
  }
  $form = array();
  $activityTypes = civicrm_api3('constant', 'get', array('name' => 'activityType'));
  asort($activityTypes['values']);
  $activityStatuses = civicrm_api3('constant', 'get', array('name' => 'activityStatus'));
  asort($activityStatuses['values']);
  $form['activity_type_id'] = array(
    '#type' => 'select',
    '#title' => t('Activity Type'),
    '#options' => $activityTypes['values'],
    '#required' => TRUE,
    '#description' => t('Type of Activity to Create'),
    '#default_value' => isset($settings['activity_type_id']) ? $settings['activity_type_id'] : NULL,
  );
  $form['activity_status_id'] = array(
    '#type' => 'select',
    '#title' => t('Activity Status'),
    '#options' => $activityStatuses['values'],
    '#required' => TRUE,
    '#description' => t('Status of Activity'),
    '#default_value' => isset($settings['activity_status_id']) ? $settings['activity_status_id'] : array_search(ts('Scheduled'), $activityStatuses['values']),
  );
  $form['assignee_contact_id'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Enter the contact you wish the activity to be assigned to'),
    '#description' => t('The activity will be assigned to the person with this contact id'),
    '#default_value' => isset($settings['assignee_contact_id']) ? $settings['assignee_contact_id'] : NULl,
  );

  return $form;
}

/**
 * Syncronizes the status of an order from Ubercart to CiviCRM
 *
 * @param $order
 *    Order
 */
function uc_civicrm_syncronize_status($order) {
  if (!module_exists('civicrm')) { return; }
  civicrm_initialize();
  require_once 'CRM/Core/Config.php';
  $config =& CRM_Core_Config::singleton();
  require_once "api/v2/Contribute.php";

  $searchParams = array('invoice_id' => $order->order_id ."_uc", 'return.contact_id' => 1,);

  $result =& civicrm_contribution_search($searchParams);

  if (civicrm_error ($result)) {
    watchdog('uc_civicrm', 'uc_civicrm_syncronize_status() returned: '. $result['error_message'], array(), WATCHDOG_ERROR);
  } else {
    $contribution = array_shift($result);
    $setParams = array(
      'id'                     => $contribution['contribution_id'],
      'contact_id'             => $contribution['contact_id'],
      'contribution_status_id' => _uc_civicrm_map_contribution_status($order->order_status),
    );

    $result =& civicrm_contribution_add($setParams);
  }
}


/**
 * Create string to insert for purchase activity details.
 */
function _uc_civicrm_create_detail_string($order) {
  $str = '';
  $n = 1;
  foreach ($order->products as $product) {
    if ($n > 1) { $str .= ', '; }
    $str .= $product->title;
    $n++;
  }

  return $str;
}

function _uc_civicrm_customer_orders_count($uid) {
  $query = "
    SELECT count(*) c
    FROM {uc_orders} uc_orders
    WHERE uid = %d
      AND order_status IN  " . uc_order_status_list('general', TRUE) . "
    ORDER BY created DESC
    LIMIT 50
  ";
  $result = db_query($query, array($uid));
  while ($order = db_fetch_object($result)) {
    return $order->c;
  }
}
/**
 * Displays a list of orders made by a customer. Originally from uc_order.module but added here when it was removed from that module.
 *
 * @see http://drupal.org/node/1567946
 *
 * @param $uid
 *   The user id of the customer.
 */
function _uc_civicrm_customer_orders($uid) {
  $query = "
    SELECT *
    FROM {uc_orders} uc_orders
    WHERE uid = %d
      AND order_status IN  " . uc_order_status_list('general', TRUE) . "
    ORDER BY created DESC
    LIMIT 50
  ";
  $result = db_query($query, $uid);
  $html = "<table><tr>
    <td>" . t('View') . "</td>
    <td>" . t('Order ID') . "</td>
    <td>" . t('Date') . "</td>
    <td>" . t('Billing name') . "</td>
    <td>" . t('Shipping name') . "</td>
    <td>" .  t('Items') . "</td>
    <td>" . t('Total') . "</td>
    <tr>";

  $totals = array('orders' => 0, 'items' => 0, 'total' => 0);

   while ($order = db_fetch_object($result)) {
    $icons = l(uc_store_get_icon('file:order_view'), 'admin/store/orders/' . $order->order_id, array(
      'html' => TRUE,
      'attributes' => array('title' => t("View order !order_id.", array('!order_id' => $order->order_id))),
    ));
    $icons .= l(uc_store_get_icon('file:order_edit'), 'admin/store/orders/' . $order->order_id . '/edit', array(
      'html' => TRUE,
      'attributes' => array('title' => t("Edit order !order_id.", array('!order_id' => $order->order_id))),
    ));
    $bname = drupal_ucfirst($order->billing_first_name) . ' ' . drupal_ucfirst($order->billing_last_name);
    $sname = drupal_ucfirst($order->delivery_first_name) . ' ' . drupal_ucfirst($order->delivery_last_name);
    $item_count = db_result("SELECT COUNT(*) FROM {uc_order_products} WHERE order_id = :order_id", array(':order_id' => $order->order_id));

    $totals['orders'] += 1;
    $totals['items'] += $item_count;
    $totals['total'] += $order->order_total;

    $html .= "<tr>
      <td>" . $icons . "</td>
      <td>" .  $order->order_id . "</td>
      <td>" .  format_date($order->created, 'uc_store') . "</td>
      <td>" .  check_plain($bname) . "</td>
      <td>" .  check_plain($sname) . "</td>
      <td>" .  $item_count['COUNT(*)'] . "</td>
      <td>" .  $order->order_total . "</td><tr>";

  }
  return $html;
}

/**
 * Implementation of hook_form_alter().
 *
 * @todo is this just one form? we can put it in the fn name can't we
 */
function uc_civicrm_form_alter(&$form, $form_state, $form_id){
  $forms = array('uc_cart_checkout_form');
  if(!in_array($form_id, $forms) || !civicrm_initialize() || (user_is_logged_in() == FALSE)) {
    return;
  }
  /*
  * Global $user to get the uid of the current user. Then load that user
  * into the variable $account.
  */
  global $user;
  try {
    $prefillAddresses = $prefillPhones = $primaryAddress = array();
    $contactID = civicrm_api3('uf_match', 'getvalue', array('return' => 'contact_id', 'uf_id' => $user->uid));
    $contact = civicrm_api3('contact', 'getsingle', array('id' => $contactID, 'return' => 'first_name, last_name'));
    $addresses = civicrm_api3('address', 'get', array('contact_id' => $contactID,));
    $phones = civicrm_api3('phone', 'get', array('contact_id' => $contactID));
    $locations = _uc_civicrm_get_locations();
    $addressTypes = array('billing', 'delivery');
    foreach ($addressTypes as $addressType) {
      foreach ($addresses ['values'] as $address) {
        $locationName = array_search($address ['location_type_id'], $locations);
        if ($locationName == 'civicrm-' . $addressType || (empty($prefillAddresses[$addressType]) && $locationName == 'uc-' . $addressType)) {
          $prefillAddresses[$addressType] = $address;
        }
        if ($address ['is_primary']) {
          $primaryAddress = $address;
        }
      }
      foreach ($phones['values'] as $phone) {
        $locationName = array_search($phone ['location_type_id'], $locations);
        if ($locationName == 'civicrm-' . $addressType || (empty($prefillPhones[$addressType]) && $locationName == 'uc-' . $addressType)) {
          $prefillPhones[$addressType] = $phone;
        }
        if ($phone['is_primary']) {
          $primaryPhone = $phone;
        }
      }
      if (empty($prefillAddresses[$addressType]) && ! empty($primaryAddress)) {
        $prefillAddresses[$addressType] = $primaryAddress;
      }
      if (empty($prefillPhones[$addressType]) && ! empty($primaryAddress)) {
        $prefillPhones[$addressType] = $primaryPhone;
      }
    }
  }
  catch (CiviCRM_API3_Exception $e) {
    watchdog('uc_civicrm', 'uc_civicrm_form_alter:' . $e->getMessage(), array(), WATCHDOG_ERROR);
    return;
  }


   //In the case of Ubercart's checkout form auto-populate the delivery and billing pane information with the appropriate addresses.
   
  foreach ($addressTypes as $addressType) {
    $pane = &$form['panes'][$addressType];
    $pane[$addressType . '_first_name']['#default_value'] = CRM_Utils_Array::value('first_name', $contact);
    $pane[$addressType . '_last_name']['#default_value'] = CRM_Utils_Array::value('last_name', $contact);
    if (!empty($prefillAddresses[$addressType])) {
      $prefill = $prefillAddresses[$addressType];
      $pane[$addressType . '_company']['#default_value'] = CRM_Utils_Array::value('name', $prefill);
      $pane[$addressType . '_street1']['#default_value'] = CRM_Utils_Array::value('street_address', $prefill);
      $pane[$addressType . '_street2']['#default_value'] = CRM_Utils_Array::value('supplemental_address_1', $prefill);
      $pane[$addressType . '_city']['#default_value'] = CRM_Utils_Array::value('city', $prefill);
      $pane[$addressType . '_postal_code']['#default_value'] = CRM_Utils_Array::value('postal_code', $prefill);


      // set state
      $stateName = _uc_civicrm_get_option_name('stateProvince', CRM_Utils_Array::value('state_province_id', $prefill));
      $country_name = _uc_civicrm_get_option_name('country', CRM_Utils_Array::value('country_id', $prefill));
      $country_id = _uc_civicrm_get_country_id($country_name);
      $pane[$addressType . '_zone'] = uc_zone_select(uc_get_field_name('zone'), NULL, NULL, $country_id, 'name', uc_address_field_required('zone'));
      if (count($pane[$addressType . '_zone']['#options']) == 1) {
        $pane[$addressType . '_zone']['#required'] = FALSE;
      }
      $stateOption = array_search($stateName, array_map('strtolower', $pane[$addressType . '_zone']['#options']));
      $pane[$addressType . '_zone']['#default_value'] = $stateOption;

      // Set country.
      $countryOption = array_search($country_name, array_map('strtolower', $pane[$addressType . '_country']['#options']));
      $pane[$addressType . '_country']['#default_value'] = $countryOption;

      // Trigger shipping calculation via javascript.
      if($addressType == 'delivery') {
        add_autocalc_shipping_js();
      }
    }
    if (!empty($prefillPhones[$addressType])) {
      $prefill = $prefillPhones[$addressType];
      $pane[$addressType . '_phone']['#default_value'] = CRM_Utils_Array::value('phone', $prefill);
    }
  }
}

/**
 * Get available locations (pref set types by variable in future instead of hard-coding types
 * UC Fields are stored to civicrm fields are prefilled from
 *
 * We don't provide a form for this yet but you can configure using
 *  drush php-eval "variable_set('uc_civicrm_locations', array('civicrm-delivery' => 1));"
 *
 * (note your location will be merged into the pre-set ones so you can set between 1 & 4)
 * @return array
 */
function _uc_civicrm_get_locations() {
  $locations = variable_get('uc_civicrm_locations', array());
  $locationTypes = civicrm_api3('phone', 'getoptions', array('field' => 'location_type_id'));
  $locations = array_merge(array(
    'civicrm-billing' => array_search('Billing', $locationTypes),
    'uc-billing' => array_search('Ubercart_Billing', $locationTypes),
    'civicrm-delivery' => array_search('Postal', $locationTypes),
    'uc-delivery' => array_search('Ubercart_Shipping', $locationTypes),
  ), $locations);
  return $locations;
}

/**
 * Return Ubercart id for a country.
 * @param string $country_name
 *   Country name to lookup, e.g. Australia.
 * @return string
 *   Ubercart id used in select options.
 */
function _uc_civicrm_get_country_id($country_name) {
  $country_data = uc_get_country_data(array('country_name' => $country_name));
  $country = current($country_data);
  return $country['country_id'];
}

/**
 * Get lower case state name from id
 * in 4.4 & above getoptions is better than constant get - but not supported in 4.2, 4.3
 * @param $id stateprovince id
 * @return string
 */
function _uc_civicrm_get_option_name($option, $id, $fn = 'strtolower') {
  $names = civicrm_api3('constant', 'get', array('name' => $option));
  return $fn($names['values'][$id]);
}

/**
 * Cal shipping for on prefill
 * https://drupal.org/node/1664858
 * @param unknown $form
 * @param unknown $form_state
 * @param unknown $form_id
 */
function add_autocalc_shipping_js(){
  drupal_add_js('$(document).ready(function(){
      $("input[id*=quote-button]").click().hide();
      $("#edit-panes-delivery-delivery-zone-wrapper").change(function(){
        $("input[id*=quote-button]").click();
      });
      $("#edit-panes-delivery-delivery-country").change(function(){
        $("input[id*=quote-button]").click();
      });
    });', 'inline');
}
